baseURL = 'https://blog.stark.us.ci/'
languageCode = 'zh-cn'
title = 'King Song 的博客'
theme = 'PaperMod'

[pagination]
pagerSize = 10

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true

[menu]

[[menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "search"
name = "搜索"
url = "/search/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 30

[params.comments]
enabled = true

[params.comments.giscus]
repo = "starksong/myblog"
repoId = "R_kgD0SYtJqw"
category = "Announcements"
categoryId = "DIC_kwD0SYtJq84C8t62"
mapping = "pathname"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "preferred_color_scheme"
lang = "zh-CN"